name: Build Windows Installer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      # 4️⃣ Build executable using PyInstaller
      - name: Build executable
        run: |
          pyinstaller --onefile --noconsole main.py -n MnyaziTracker
        working-directory: Mnyazi_Tracker_Package

      # 5️⃣ Install Inno Setup
      - name: Install Inno Setup
        run: choco install innosetup --yes

      # 6️⃣ Compile installer (fixed PowerShell syntax)
      - name: Compile installer
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "installer_script.iss"
        working-directory: Mnyazi_Tracker_Package

      # 7️⃣ Upload installer as artifact
      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mnyazi_Tracker_Installer
          path: Mnyazi_Tracker_Package\Output\Mnyazi_Tracker_Installer.exe





